# Generated by Django 3.1.2 on 2020-10-16 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_auto_20201016_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default=datetime.datetime(2020, 10, 16, 2, 23, 10, 673374, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
