# Generated by Django 3.1.2 on 2020-10-16 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_authors_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default=datetime.datetime(2020, 10, 16, 22, 50, 47, 922246, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
